version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: flask_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: flaskdb
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - flask_network

  adminer:
    image: adminer
    container_name: flask_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - flask_network

volumes:
  mysql_data:

networks:
  flask_network:
    driver: bridge
