"""Add product_detail_images table

Revision ID: 9875c428b6bc
Revises: e7d41e5a92c4
Create Date: 2024-09-29 03:14:51.551658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9875c428b6bc'
down_revision = 'e7d41e5a92c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_detail_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('img_path', sa.String(length=255), nullable=True),
    sa.Column('active', sa.String(length=1), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_detail_images')
    # ### end Alembic commands ###
